spring.datasource.url=jdbc:postgresql://localhost:5433/gym_tracker
spring.datasource.username=gym_user
spring.datasource.password=gym_password
spring.jpa.show-sql=true
logging.level.com.satveer27.gym_tracker_api=DEBUG