spring.jpa.show-sql=true
logging.level.com.satveer27.gym_tracker_api=DEBUG
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.diskspace.enabled=false
management.health.ssl.enabled=false